import React, { useMemo } from "react";
import {
  PDFDownloadLink,
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

/**
 * ReportsPDFView
 * -------------------------------------------------------------
 * Pass 2 of the Reports rewrite. Wraps `@react-pdf/renderer`'s
 * `PDFDownloadLink` so the user can save the same dossier shown
 * in the HTML view as a PDF. The PDF is intentionally simple —
 * cover, executive summary, hazard table, references — and is
 * easy to extend section-by-section by porting individual
 * `pdf*.jsx` files from the original ToxIntelligence repo.
 */
const pdfStyles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1f2937",
  },
  h1: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 6,
    color: "#111827",
  },
  h2: {
    fontSize: 14,
    fontWeight: 700,
    marginTop: 16,
    marginBottom: 6,
    color: "#1e2c44",
    borderBottom: 1,
    borderColor: "#d1d5db",
    paddingBottom: 2,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 4,
  },
  table: { marginTop: 6 },
  row: { flexDirection: "row", borderBottom: 1, borderColor: "#e5e7eb", paddingVertical: 3 },
  cellKey: { width: "40%", fontSize: 10, color: "#6b7280" },
  cellVal: { width: "60%", fontSize: 10, color: "#1f2937" },
  meta: { color: "#6b7280", fontSize: 10, marginTop: 4 },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 9,
    color: "#9ca3af",
    borderTop: 1,
    borderColor: "#e5e7eb",
    paddingTop: 6,
    textAlign: "center",
  },
});

function ReportDocument({ report, query }) {
  const compound = report.compounds?.primary || report.compound || {};
  const ai = report.ai_summary || {};
  const hazards = report.hazards || report.hazard_summary || {};
  const sources = report.data_sources || {};

  const profileRows = [
    ["Compound", compound.name || query || "—"],
    ["CAS", compound.cas_number],
    ["ChEMBL ID", compound.chembl_id],
    ["PubChem CID", compound.pubchem_cid],
    ["Formula", compound.molecular_formula],
    ["MW", compound.molecular_weight],
    ["SMILES", compound.smiles],
  ].filter(([, v]) => v != null && v !== "");

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.h1}>{compound.name || query || "Toxicology dossier"}</Text>
        <Text style={pdfStyles.meta}>
          Scope: {report.evaluation_scope || "compound"}
          {report.target_route ? ` • Route: ${report.target_route}` : ""}
        </Text>

        <Text style={pdfStyles.h2}>1. Compound profile</Text>
        <View style={pdfStyles.table}>
          {profileRows.map(([k, v]) => (
            <View key={k} style={pdfStyles.row}>
              <Text style={pdfStyles.cellKey}>{k}</Text>
              <Text style={pdfStyles.cellVal}>{String(v)}</Text>
            </View>
          ))}
        </View>

        <Text style={pdfStyles.h2}>2. Executive summary</Text>
        <Text style={pdfStyles.body}>
          {ai.summary
            ? ai.summary
            : ai.error
              ? `${ai.error}${ai.note ? ` (${ai.note})` : ""}`
              : "No AI summary available; populate /report/generate AI keys to enable narrative output."}
        </Text>

        <Text style={pdfStyles.h2}>3. Hazard endpoints</Text>
        {Object.keys(hazards).length === 0 ? (
          <Text style={pdfStyles.body}>No hazard data attached to this report.</Text>
        ) : (
          <View style={pdfStyles.table}>
            {Object.entries(hazards).map(([k, v]) => (
              <View key={k} style={pdfStyles.row}>
                <Text style={pdfStyles.cellKey}>{prettify(k)}</Text>
                <Text style={pdfStyles.cellVal}>
                  {typeof v === "object" ? JSON.stringify(v) : String(v)}
                </Text>
              </View>
            ))}
          </View>
        )}

        <Text style={pdfStyles.h2}>4. Source coverage</Text>
        {Object.keys(sources).length === 0 ? (
          <Text style={pdfStyles.body}>No source coverage data.</Text>
        ) : (
          <View style={pdfStyles.table}>
            {Object.entries(sources).map(([k, v]) => (
              <View key={k} style={pdfStyles.row}>
                <Text style={pdfStyles.cellKey}>{prettify(k)}</Text>
                <Text style={pdfStyles.cellVal}>
                  {typeof v === "object"
                    ? v?.status || `${Object.keys(v).length} keys`
                    : String(v)}
                </Text>
              </View>
            ))}
          </View>
        )}

        <Text style={pdfStyles.footer}>
          Generated by Tulip Toxicology workspace. Demonstration report only —
          confirm all values against the underlying source data before use.
        </Text>
      </Page>
    </Document>
  );
}

export default function ReportPDFView({ report, query }) {
  // Memoize so the PDF doesn't rebuild on every render of the parent.
  const doc = useMemo(
    () => <ReportDocument report={report} query={query} />,
    [report, query],
  );

  return (
    <div style={{ margin: "12px 0" }}>
      <PDFDownloadLink
        document={doc}
        fileName={`tox-dossier-${slug(query)}.pdf`}
        style={pdfLinkStyle}
      >
        {({ loading }) => (loading ? "Preparing PDF..." : "Download dossier PDF")}
      </PDFDownloadLink>
    </div>
  );
}

const pdfLinkStyle = {
  display: "inline-block",
  background: "rgb(69 112 182)",
  color: "#fff",
  padding: "8px 14px",
  borderRadius: 6,
  fontSize: 13,
  textDecoration: "none",
};

function prettify(key) {
  return String(key)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function slug(s) {
  return String(s || "report")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}
